#!/usr/bin/env bash
set -e

echo files changed: $(git diff HEAD^ HEAD --diff-filter=ACDMR --name-only | wc -l)

umask 002

echo "Check whether to reinstall python packages"
git diff-tree -r --name-only --no-commit-id HEAD^ HEAD | if grep --quiet -e ".cfg" -e 'setup.py'
then
  bin/buildout
fi

echo "Restarting xenian_channel.bot.service"
systemctl restart xenian_channel_bot.service
echo "Restarted"
